/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ProyectoGym;

import AccesoDatos.ProyectoGym.SocioData;
import Entidades.ProyectoGym.Socio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javi
 */
public class SocioConsultaVista extends javax.swing.JInternalFrame {

private SocioData socioData;


    public SocioConsultaVista() {
        initComponents();
         socioData = new SocioData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BuscarID = new javax.swing.JButton();
        textId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ListarBoton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        limpiarBoton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Socio Consultas");

        jLabel2.setText("Buscar Socio por Dni:");

        BuscarID.setText("Buscar");
        BuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIDActionPerformed(evt);
            }
        });

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombre", "Apellido", "Edad", "Correo", "Teléfono", "Asistencias"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ModificarBoton.setText("Modificar Socio");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar Socio");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Recuerda modificar desde la tabla");

        ListarBoton.setText("Listar");
        ListarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBotonActionPerformed(evt);
            }
        });

        jLabel4.setText("Listar Todos los socios:");

        limpiarBoton.setText("Limpiar");
        limpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBotonActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BuscarID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ModificarBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(EliminarBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ListarBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(limpiarBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(ModificarBoton)
                .addGap(80, 80, 80)
                .addComponent(EliminarBoton)
                .addGap(245, 245, 245))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarID))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jLabel3))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(limpiarBoton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ListarBoton)
                .addGap(92, 92, 92))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ListarBoton)
                        .addComponent(jLabel4))
                    .addComponent(BuscarID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(limpiarBoton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
     
    }//GEN-LAST:event_textIdActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
                                                             
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada != -1) {
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de modificar este socio?", "Confirmar Modificación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            int idSocio = (int) jTable1.getValueAt(filaSeleccionada, 0);
            String dni = (String) jTable1.getValueAt(filaSeleccionada, 1);
            String nombre = (String) jTable1.getValueAt(filaSeleccionada, 2);
            String apellido = (String) jTable1.getValueAt(filaSeleccionada, 3);
            int edad = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 4).toString());
            String correo = (String) jTable1.getValueAt(filaSeleccionada, 5);
            String telefono = (String) jTable1.getValueAt(filaSeleccionada, 6);
            int asistencia = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 7).toString());

            Socio socio = new Socio(idSocio, dni, nombre, apellido, edad, correo, telefono);
            socio.setContador_asistencia(asistencia);
            socioData.modificarSocio(socio);
            
            
            jTable1.setValueAt(dni, filaSeleccionada, 1);
            jTable1.setValueAt(nombre, filaSeleccionada, 2);
            jTable1.setValueAt(apellido, filaSeleccionada, 3);
            jTable1.setValueAt(edad, filaSeleccionada, 4); 
            jTable1.setValueAt(correo, filaSeleccionada, 5);
            jTable1.setValueAt(telefono, filaSeleccionada, 6);
            jTable1.setValueAt(asistencia, filaSeleccionada, 7);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un socio de la tabla para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
       int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada != -1) {
        int idSocio = (int) jTable1.getValueAt(filaSeleccionada, 0);
        eliminarSocio(idSocio);
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un socio de la tabla para eliminar.");
    }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void BuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIDActionPerformed
        try {
        String dni = textId.getText();
        buscarSocioPorDni(dni);
        
        ModificarBoton.setEnabled(true);
        EliminarBoton.setEnabled(true);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un DNI válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BuscarIDActionPerformed

    private void ListarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBotonActionPerformed
      listarSocios();
      ModificarBoton.setEnabled(false); 
    EliminarBoton.setEnabled(false); 
    }//GEN-LAST:event_ListarBotonActionPerformed

    private void limpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBotonActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
     ModificarBoton.setEnabled(false); 
    EliminarBoton.setEnabled(false); 
    }//GEN-LAST:event_limpiarBotonActionPerformed



public void buscarSocioPorDni(String dni) {
    if (dni.matches("\\d{8}")) {
        Socio socio = new Socio();
        socio = socioData.buscarSocioPorDni(dni);
        if (socio != null && !socio.getApellido().isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            modelo.addRow(new Object[]{socio.getId_socio(), socio.getDni(), socio.getNombre(), socio.getApellido(),
                socio.getEdad(), socio.getCorreo(), socio.getTelefono(), socio.getContador_asistencia()});
        } else {
            JOptionPane.showMessageDialog(null, "El Socio no existe o fue dado de baja...");
        }
    } else {
        JOptionPane.showMessageDialog(null, "El DNI debe contener exactamente 8 caracteres numéricos.");
    }
}

    public void listarSocios() {
        List<Socio> socios = socioData.listarSocios();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 
        for (Socio socio : socios) {
            modelo.addRow(new Object[]{socio.getId_socio(), socio.getDni(), socio.getNombre(), socio.getApellido(),
                socio.getEdad(), socio.getCorreo(), socio.getTelefono(), socio.getContador_asistencia()});
        }
    }

    public void eliminarSocio(int id) {
        socioData.eliminarSocio(id);
        JOptionPane.showMessageDialog(null, "Socio eliminado correctamente.");
        listarSocios(); 
    }
    
  

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarID;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton ListarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpiarBoton;
    private javax.swing.JTextField textId;
    // End of variables declaration//GEN-END:variables
}
